Repository gisce/oopgrade, pull requests merged in 2023-10, with the labels that each got.

#32 NEW delete_record function
  oopgrade/oopgrade.py
  setup.py
Labels: enhancement

#33 Fix requirements
  setup.py
Labels: bug

#35 configparser compat py2/py3
  oopgrade/cli.py
Labels: enhancement

#36 Ci and tests
  .bumpversion.cfg
  .github/workflows/tag.yml
  .github/workflows/tests.yml
  requirements-dev.txt
  spec/data_migration_spec.py
Labels: patch, CI, to be merged
