Repository gisce/oopgrade, pull requests merged in 2024-08, with the labels that each got.

#49 Permitir cargar todos los registros del fichero que coincidan con el id de registro a actualizar
  oopgrade/oopgrade.py
Labels: enhancement

#48 New method load_translation
  oopgrade/oopgrade.py
Labels: minor, to be merged

#45 Eliminar los shortcuts de las vistas a eliminar
  oopgrade/oopgrade.py
Labels: bug, patch

#51 Fix delete record function
  oopgrade/oopgrade.py
Labels: bug, patch
