Repository gisce/oopgrade, pull requests merged in 2025-01, with the labels that each got.

#56 Fix load translation method when loading tranlations without res_id
  oopgrade/oopgrade.py
Labels: bug, patch

#57 Use ubuntu-22.04 image
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: minor, CI

#58 Update setup with long_description_content_type
  setup.py
Labels: patch

#59 Update README use md
  README.md
  README.rst
  setup.py
Labels: patch
